version: "3"

services: 
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: teste  
      POSTGRES_PASSWORD: teste123
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"